import{S as g,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const y="47392920-efce9c2b3427e3353db7767ab",b="https://pixabay.com/api/";function m(t,n=1,o=20){const r=`${b}?key=${y}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${o}&page=${n}`;return fetch(r).then(e=>{if(!e.ok)throw new Error("Failed to fetch data");return e.json()}).then(e=>{if(e.hits.length===0)throw new Error("No images found");return e})}function L(t){t.innerHTML=""}function h(t,n){const o=t.map(r=>`
        <a class="gallery__item" href="${r.largeImageURL}">
          <img class="gallery__image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
          <div class="info">
            <p><b>Likes:</b> ${r.likes}</p>
            <p><b>Views:</b> ${r.views}</p>
            <p><b>Comments:</b> ${r.comments}</p>
            <p><b>Downloads:</b> ${r.downloads}</p>
          </div>
        </a>
      `).join("");n.insertAdjacentHTML("beforeend",o)}const $=document.querySelector(".search-form"),d=document.querySelector(".gallery"),a=document.querySelector(".load-more");let f="",i=1;const l=20;let p=new g(".gallery a");$.addEventListener("submit",w);a.addEventListener("click",E);function w(t){t.preventDefault();const n=t.target.elements.searchQuery.value.trim();if(n===""){c.error({title:"Error",message:"Search query cannot be empty!"});return}f=n,i=1,L(d),m(f,i,l).then(o=>{h(o.hits,d),p.refresh(),o.totalHits>l?a.classList.remove("is-hidden"):a.classList.add("is-hidden"),c.success({title:"Success",message:`Found ${o.totalHits} images!`})}).catch(o=>{c.error({title:"Error",message:o.message})})}function E(){i+=1,m(f,i,l).then(t=>{h(t.hits,d),p.refresh(),i*l>=t.totalHits&&a.classList.add("is-hidden")}).catch(t=>{c.error({title:"Error",message:t.message})})}
//# sourceMappingURL=index.js.map
